# version: "3.9"
services:
  jupyter:
    container_name: python-datascience
    image: jupyter/datascience-notebook
    build: ./python # Use the Dockerfile at ./python
    ports:
      - 8888:8889
    environment:
      # Set environment variables
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      # Mount Python directory to /home/chinchilla/
      - type: bind
        source: ../../..
        target: /home/chinchilla/TIL
    command: start-notebook.sh
