name: actions test
# Git_Github\github_actions\GitHubActions.md参照
on:
  push:
    branches:
        - actions_test
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      contents: write # フォーマット後のコードをコミット（書き込む）ために必要
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11' #Ver指定がある場合はここで指定
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip            
            pip install -r ./Git_Github/requirements.txt
        - name: Test with pytest
          run: |
            pip install pytest pytest-cov
            pytest -v 
        - name: Format with black
          run: |
            pip install black
            black .
        # blackのフォーマッターが実施済みか確認するコマンド
        # - uses: psf/black@stable
        #   with:
        #     src: "./"

        # フォーマット後のコードをコミット
        - uses: stefanzweifel/git-auto-commit-action@v3.0.0
          with:
            commit_message: Apply Code Formatter Change
            ref: ${{ github.head_ref }}