name: actions test

on:
  push:
    branches:
        - actions_test
  workflow_dispatch:

jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps: # 'steps' セクションを追加。何かしらのステップをここに記述する必要があります。
      - name: Example step
        run: echo "This is an example step for the 'build' job."

  CI:
    runs-on: ubuntu-latest 
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.11' #requirements.txtのモジュールが3.12以降を想定していないため
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip            
            pip install -r ./Git_Github/requirements.txt
        - name: Test with pytest
          run: |
            pip install pytest pytest-cov
            pytest -v 
        - name: Install Poetry
          run: |
            curl -sSL https://install.python-poetry.org | python - 
            #Poetryの最新URLに変更
        - name: Add path for Poetry
          run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
        - name: Install Dependencies
          run: poetry install --no-interaction
        - name: black
          run: poetry run black .
        - name: autoflake
          run: poetry run autoflake -r .
        - uses: stefanzweifel/git-auto-commit-action@v3.0.0
          with:
            commit_message: Apply Code Formatter Change
            ref: ${{ github.head_ref }}