name: actions test

on:
  push:
  workflow_dispatch:

jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps: # 'steps' セクションを追加。何かしらのステップをここに記述する必要があります。
      - name: Example step
        run: echo "This is an example step for the 'build' job."

  CI:
    runs-on: ubuntu-latest 
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip            pip install -r ./Git_Github/requirements.txt