name: actions test

on:
  push:
  workflow_dispatch:

jobs:
  echo_test:
    runs-on: ubuntu-latest
    steps: # 'steps' セクションを追加。何かしらのステップをここに記述する必要があります。
      - name: Example step
        run: echo "This is an example step for the 'build' job."

  CI:
    runs-on: ubuntu-latest 
    strategy:
        matrix:
          python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
    steps: 
      - name: Hoge step
        run: echo Hoge
